### PR TITLE
💥 merge admin and mailer api into a single binary

### LINKED ISSUE #48: Merge api and mailer in one single binary
We can marge dispatcher, api and mailer in a single binary with option to choose with part of the application to run.

- Mailer can listen on port 50051
- Api can listen on port 50052

### PR DESCRIPTION
**Pull request by ludusrusso**
**What this PR does / why we need it**:
Merge admin and mailer api into a single binary.

ADMIN listening on port 50051
MAILER listening on port 50052

**Which issue(s) this PR fixes**  
Fixes #48

### CODE REVIEW

**Comment by ludusrusso** [comment]
@davideimola I see mailer test in CI but it should not be there. Not sure if this happen since I'm in a PR

**Comment by davideimola** [comment]
What do you mean? @ludusrusso

**Comment by ludusrusso** [comment]
I've removed the build of mailer, but I see it in pending state in checks.

**Comment by davideimola** [comment]
You have to remove the CI as required in the repository settings!

**Pull request merged**
